import type { ContentWarning } from "@engine/types";

/**
 * UI grouping for the content-warning checklist. The engine doesn't
 * care about groups — render order in the description follows the
 * user's selection order in the array — but the editor uses these
 * groups to render collapsible sections so 40+ items are scannable.
 *
 * Add a new warning by:
 * 1. Appending the id to {@link CONTENT_WARNINGS} in `@engine/types`.
 * 2. Adding it to one of these groups (UI placement).
 * 3. Translating `description.contentWarnings.items.{id}` in all locales
 *    + the editor's `editor.contentWarningOptions.{id}` short label.
 */
export interface ContentWarningGroup {
  id: string;
  /** i18n key for the group heading shown in the editor. */
  labelKey: string;
  items: ContentWarning[];
}

export const CONTENT_WARNING_GROUPS: readonly ContentWarningGroup[] = [
  {
    id: "spoilers",
    labelKey: "editor.contentWarningGroups.spoilers",
    items: [
      "spoiler_story",
      "spoiler_ending",
      "spoiler_true_ending",
      "spoiler_post_game",
      "spoiler_secret_ending",
      "spoiler_dlc",
    ],
  },
  {
    id: "photosensitive",
    labelKey: "editor.contentWarningGroups.photosensitive",
    items: [
      "flashing_lights",
      "motion_sickness",
      "migraine_trigger",
      "strobe_effects",
      "screen_shake_intense",
      // v0.23.0: VFX intensity — share the photosensitive audience.
      "lens_flare_intense",
      "bloom_excessive",
      "particle_effects_dense",
      "screen_overlay_flashing",
      "color_saturation_extreme",
      "motion_blur_heavy",
      "depth_of_field_aggressive",
      "post_processing_intense",
    ],
  },
  {
    id: "audio",
    labelKey: "editor.contentWarningGroups.audio",
    items: [
      "loud_noises",
      "ear_piercing",
      "jumpscare_audio",
      "sudden_volume_changes",
      "distorted_audio",
      "screeching_metallic",
      "persistent_high_pitch",
      "audio_glitches",
      "heavy_bass_rumble",
      "screaming_audio",
      "glass_breaking_audio",
      "microphone_pops",
      "white_noise_static",
    ],
  },
  {
    id: "dialogue",
    labelKey: "editor.contentWarningGroups.dialogue",
    items: [
      "profanity_frequent",
      "sexual_innuendo",
      "inflammatory_speech",
      "verbal_abuse",
      "threatening_language",
      "slurs_derogatory",
      "crude_humor",
      "mature_humor",
      "dark_humor",
      "drug_references",
    ],
  },
  {
    id: "phobias",
    labelKey: "editor.contentWarningGroups.phobias",
    items: [
      "jump_scares",
      "acrophobia",
      "trypophobia",
      "thalassophobia",
      "claustrophobia",
      "arachnophobia",
      "entomophobia",
      "ophidiophobia",
      "cynophobia",
      "nyctophobia",
      "pyrophobia",
      "pediophobia",
      "hemophobia",
      "coulrophobia",
      "ablutophobia",
      "taphophobia",
      "automatonophobia",
      "megalophobia",
      "submechanophobia",
      "necrophobia",
      "spectrophobia",
      "demonophobia",
      "selachophobia",
      "mysophobia",
      "emetophobia",
      "scopophobia",
      "monophobia",
      "musophobia",
      "chiroptophobia",
      "ornithophobia",
      "ichthyophobia",
      "herpetophobia",
      "katsaridaphobia",
      "apiphobia",
      "astraphobia",
      "agoraphobia",
      "enochlophobia",
      "chionophobia",
      "nosocomephobia",
      "aichmophobia",
      "pnigophobia",
      "homichlophobia",
      "lilapsophobia",
      "ombrophobia",
      "nephophobia",
      "ancraophobia",
      "cryophobia",
      "heliophobia",
      "cymophobia",
      "limnophobia",
      "potamophobia",
      "chromophobia",
      "erythrophobia",
      "xanthophobia",
      "leukophobia",
      "melanophobia",
    ],
  },
  {
    id: "mental_health",
    labelKey: "editor.contentWarningGroups.mental_health",
    items: [
      "anxiety_inducing",
      "depression_themes",
      "eating_disorders",
      "substance_use",
      "self_harm",
      "ptsd_themes",
      "needles",
      "body_fluids",
      "pregnancy_horror",
      "illness_themes",
      "bipolar_themes",
      "ocd_themes",
      "panic_attacks",
      "dissociation",
      "paranoia_themes",
      "intrusive_thoughts",
      "medical_horror",
    ],
  },
  {
    id: "social_phenomena",
    labelKey: "editor.contentWarningGroups.social_phenomena",
    items: [
      "autism_themes",
      "adhd_themes",
      "hikikomori",
      "neet_themes",
      "social_anxiety_themes",
      "social_isolation",
      "schizophrenia_themes",
      "burnout_themes",
      "survivor_guilt",
      "abandonment_themes",
      "parasocial_themes",
      "gaslighting_themes",
      "stockholm_syndrome",
      "behavioral_addiction",
      "existential_crisis",
      "impostor_syndrome",
      "midlife_crisis",
      "quarter_life_crisis",
      "workplace_harassment",
      "masculinity_pressure",
      "body_shaming",
      "beauty_standards",
    ],
  },
  {
    id: "internet_digital",
    labelKey: "editor.contentWarningGroups.internet_digital",
    items: [
      "cyberbullying",
      "doxxing",
      "trolling_griefing",
      "cancel_culture",
      "social_media_addiction",
      "doomscrolling",
      "fomo",
      "fake_news",
      "online_scams",
      "catfishing",
      "deepfake_themes",
      "cyberstalking",
      "internet_challenges",
      "influencer_culture",
      "online_radicalization",
      "loot_boxes",
      "ai_themes",
      "data_privacy",
    ],
  },
  {
    id: "sensitive",
    labelKey: "editor.contentWarningGroups.sensitive",
    items: [
      "blood_gore",
      "mature_18plus",
      "revealing_outfits",
      "partial_nudity",
      "sexualized_characters",
      "fanservice",
      "suggestive_poses",
      "disturbing_imagery",
      "animal_abuse",
      "child_harm",
      "domestic_violence",
      "sexual_assault",
      "torture",
      "religion_themes",
      "war_violence",
      "discrimination",
      "police_violence",
      "smoking_drinking",
      "detailed_killing",
      "cult_occult",
      "psychological_manipulation",
      "grief_loss",
      "kidnapping",
      "hate_speech",
      "historical_atrocity",
      "slavery_themes",
      "terrorism_themes",
      "bullying_themes",
      "human_experimentation",
      "cannibalism",
      "nuclear_themes",
      "homophobia",
      "transphobia",
      "xenophobia",
      "political_extremism",
      "religious_extremism",
      "genocide",
      "holy_war",
      "holocaust_themes",
      "civil_war",
      "mass_shooting",
      "colonialism",
      "propaganda",
      "dystopian_state",
      "conspiracy_theories",
      "censorship_themes",
      "ethnic_conflict",
      "refugee_crisis",
      "revolution_themes",
      "assassination",
      "coup_themes",
      "inquisition",
      "forced_labor",
      "ultranationalism",
      "hanging_depiction",
      "drowning_depiction",
      "burning_alive",
      "asphyxiation_depiction",
      "restraint_torture",
      "public_execution",
      "decapitation",
      "impalement",
      "mass_casualty_event",
      "vehicular_violence",
      "overdose_depiction",
      "defenestration",
    ],
  },
  {
    id: "horror_specific",
    labelKey: "editor.contentWarningGroups.horror_specific",
    items: [
      "eye_horror",
      "body_horror",
      "face_horror",
      "cosmic_horror",
      "extreme_gore",
      "decay_rot",
      "mutilation",
      "liminal_spaces",
      "analog_horror",
      "unreality_themes",
      "pursuit_chase",
      "entity_horror",
    ],
  },
  {
    id: "playstyle",
    labelKey: "editor.contentWarningGroups.playstyle",
    items: [
      "blind_playthrough",
      "no_spoilers_chat",
      "casual_difficulty",
      "hardcore_difficulty",
      "permadeath_run",
      "speedrun_attempt",
      "completionist_run",
      "learning_mechanics",
      "first_time_playing",
      "returning_player",
    ],
  },
  {
    id: "gameplay_disclosure",
    labelKey: "editor.contentWarningGroups.gameplay_disclosure",
    items: [
      "mods_used",
      "cheats_enabled",
      "glitch_exploits",
      "assisted_run",
      "educational_purpose_only",
    ],
  },
] as const;
