/**
 * Security headers for every HTML response the Worker produces.
 *
 * `public/_headers` covers the static files Cloudflare serves directly, but
 * Cloudflare does not apply `_headers` rules to responses generated by Worker
 * code — so the app shell, the gate page and the static legal pages get their
 * headers here. `tests/worker/headers.test.ts` keeps the shared baseline in
 * step with `public/_headers`.
 *
 * HSTS is deliberately absent: the zone edge already sends
 * `max-age=31536000; includeSubDomains; preload`, and a second copy from the
 * origin risks a merged, malformed header.
 */

export const BASELINE_HEADERS: Readonly<Record<string, string>> = {
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Permissions-Policy":
    "accelerometer=(), camera=(), display-capture=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), midi=(), payment=(), usb=(), browsing-topics=()",
  "Cross-Origin-Opener-Policy": "same-origin",
  "Cross-Origin-Resource-Policy": "same-origin",
  "X-Frame-Options": "DENY",
};

/** CSP for the React app shell (index.html). */
export const APP_CSP = [
  "default-src 'self'",
  // Cloudflare Web Analytics beacon (manual snippet, web build only).
  "script-src 'self' https://static.cloudflareinsights.com",
  "connect-src 'self' https://cloudflareinsights.com",
  "img-src 'self' data: blob:",
  // sonner / Radix / Motion set inline styles; no inline <script> is allowed.
  "style-src 'self' 'unsafe-inline'",
  "font-src 'self' data:",
  "manifest-src 'self'",
  "worker-src 'self'",
  "object-src 'none'",
  "base-uri 'none'",
  "form-action 'self'",
  "frame-ancestors 'none'",
  "upgrade-insecure-requests",
].join("; ");

/** CSP for the Turnstile gate page — its one inline script carries a nonce. */
export function gateCsp(nonce: string): string {
  return [
    "default-src 'none'",
    `script-src 'nonce-${nonce}' 'strict-dynamic' https://challenges.cloudflare.com`,
    "frame-src https://challenges.cloudflare.com",
    "connect-src 'self'",
    "img-src 'self' data:",
    "style-src 'unsafe-inline'",
    "base-uri 'none'",
    "form-action 'self'",
    "frame-ancestors 'none'",
  ].join("; ");
}

/** CSP for the prerendered legal pages: no script at all. */
export const LEGAL_CSP = [
  "default-src 'none'",
  "img-src 'self' data:",
  "style-src 'unsafe-inline'",
  "base-uri 'none'",
  "form-action 'none'",
  "frame-ancestors 'none'",
].join("; ");

/**
 * Copy a response with the baseline headers, a CSP and a cache policy.
 * Responses from `env.ASSETS` have immutable headers, so this always rebuilds.
 */
export function withSecurityHeaders(
  response: Response,
  options: { csp: string; cacheControl: string; varyCookie?: boolean },
): Response {
  const headers = new Headers(response.headers);
  for (const [name, value] of Object.entries(BASELINE_HEADERS)) headers.set(name, value);
  headers.set("Content-Security-Policy", options.csp);
  headers.set("Cache-Control", options.cacheControl);
  if (options.varyCookie) headers.append("Vary", "Cookie");
  return new Response(response.body, {
    status: response.status,
    statusText: response.statusText,
    headers,
  });
}

/** A small plain-text response with the baseline headers. */
export function plainResponse(status: number, message: string, extra?: HeadersInit): Response {
  const headers = new Headers(extra);
  headers.set("Content-Type", "text/plain; charset=utf-8");
  headers.set("Cache-Control", "no-store");
  for (const [name, value] of Object.entries(BASELINE_HEADERS)) headers.set(name, value);
  return new Response(message, { status, headers });
}

/** A JSON response for the verify endpoint. */
export function jsonResponse(status: number, body: unknown, extra?: HeadersInit): Response {
  const headers = new Headers(extra);
  headers.set("Content-Type", "application/json; charset=utf-8");
  headers.set("Cache-Control", "no-store");
  for (const [name, value] of Object.entries(BASELINE_HEADERS)) headers.set(name, value);
  return new Response(JSON.stringify(body), { status, headers });
}
